extends:
  - "@socialgouv/eslint-config-react"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:import/typescript"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  project: './tsconfig.json'